"""
Supervisor — Execute component.
Launches Nextflow with the adaptive profile generated by the Plan,
monitors the execution and manages adaptive retry in case of OOM.
"""

from __future__ import annotations

import subprocess
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional
import os

from .log_parser import classify_failure, FailureCause


MAX_RETRIES = 3
RETRY_REDUCTION_FACTOR = 0.9  # reduces the parameter by 10% on each retry


@dataclass
class RunResult:
    success: bool
    returncode: int
    attempts: int
    failure_cause: Optional[str] = None
    log_path: Optional[str] = None


def _build_nextflow_cmd(
    pipeline: str,
    config_path: str,
    resume: bool = True,
    extra_args: list[str] = None,
) -> list[str]:
    cmd = [
        "nextflow", "run", pipeline,
        "-c", config_path,
        "-profile", "adaptive_profile",
    ]
    if resume:
        cmd.append("-resume")
    if extra_args:
        cmd.extend(extra_args)
    return cmd


def _read_maxforks_from_config(config_path: str) -> Optional[int]:
    """Reads the current value of maxForks from the generated config."""
    try:
        content = Path(config_path).read_text()
        for line in content.split("\n"):
            if "params.maxforks" in line and "=" in line:
                val = line.split("=")[1].strip()
                return int(val)
    except (OSError, ValueError):
        return None


def _update_maxforks_in_config(config_path: str, new_value: int) -> None:
    """Updates maxForks in the generated config for the retry."""
    content = Path(config_path).read_text()
    lines = []
    for line in content.split("\n"):
        if "params.maxforks" in line and "=" in line:
            lines.append(f"        params.maxforks          = {new_value}")
        elif "maxForks = " in line and "feature_extraction" not in line:
            lines.append(f"                maxForks = {new_value}")
        else:
            lines.append(line)
    Path(config_path).write_text("\n".join(lines))
    print(f"[Execute] maxForks aggiornato a {new_value} per il retry")


def supervise(
    pipeline: str,
    config_path: str,
    repo_root: str = ".",
    profile = None,
    auto: bool = False,
    extra_args: list[str] = None,
) -> RunResult:
    """
    Launches Nextflow and supervises the lifecycle of the pipeline.
    In case of OOM, reduces maxForks and retries with -resume.
    """
    Path(repo_root, "reports").mkdir(exist_ok=True)
    attempts = 0

    while attempts <= MAX_RETRIES:
        attempts += 1
        cmd = _build_nextflow_cmd(pipeline, config_path, resume=(attempts > 1), extra_args=extra_args)

        print(f"\n[Execute] Attempt {attempts}/{MAX_RETRIES + 1}")
        print(f"[Execute] Command: {' '.join(cmd)}")

        try:
          env = os.environ.copy()
          if profile and getattr(profile, 'pipeline_dsl', None) == "1":
            env["NXF_SYNTAX_PARSER"] = "v1"
            print("[Execute] DSL1 detected — setting NXF_SYNTAX_PARSER=v1 automatically")
            proc = subprocess.run(cmd, check=False, cwd=repo_root)
        except FileNotFoundError:
            print("[Execute] ERROR: nextflow not found in PATH")
            return RunResult(success=False, returncode=127, attempts=attempts, failure_cause="nextflow_not_found")
        except KeyboardInterrupt:
            print("\n[Execute] Interrupted by user")
            return RunResult(success=False, returncode=130, attempts=attempts, failure_cause="interrupted")

        if proc.returncode == 0:
            print("[Execute] Pipeline completed successfully.")
            return RunResult(success=True, returncode=0, attempts=attempts)

        # Classifica il fallimento leggendo .nextflow.log
        cause = classify_failure(str(Path(repo_root) / ".nextflow.log"))
        print(f"[Execute] Failure detected: {cause.value}")

        if cause == FailureCause.OOM_VRAM and attempts <= MAX_RETRIES:
            current = _read_maxforks_from_config(config_path)
            if current and current > 1:
                new_val = max(1, int(current * RETRY_REDUCTION_FACTOR))
                print(f"[Execute] OOM VRAM — riduco maxForks: {current} → {new_val}")
                _update_maxforks_in_config(config_path, new_val)
                time.sleep(5)
                continue

        elif cause == FailureCause.OOM_RAM and attempts <= MAX_RETRIES:
            current = _read_maxforks_from_config(config_path)
            if current and current > 1:
                new_val = max(1, int(current * RETRY_REDUCTION_FACTOR))
                print(f"[Execute] OOM RAM — riduco maxForks: {current} → {new_val}")
                _update_maxforks_in_config(config_path, new_val)
                time.sleep(5)
                continue

        else:
            # Causa non recuperabile automaticamente
            print(f"[Execute] Failure not recoverable: {cause.value}")
            print("[Execute] Consult .nextflow.log for details.")
            return RunResult(
                success=False,
                returncode=proc.returncode,
                attempts=attempts,
                failure_cause=cause.value,
            )

    print(f"[Execute] Maximum number of retries ({MAX_RETRIES}) reached.")
    return RunResult(success=False, returncode=1, attempts=attempts, failure_cause="max_retries")
